# Generated by Django 5.2 on 2025-05-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_topico_assunto_remove_topico_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('icone', models.ImageField(upload_to='reacoes/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='tag_principal',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='tags',
        ),
        migrations.AddField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='postagem',
            name='tag_sistema',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sistema': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_sistema',
            field=models.BooleanField(default=False, help_text='Tag obrigatória do sistema (ex: Dúvida, Discussão)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReacaoPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='posts.postagem')),
                ('reacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('postagem', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='TagEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_especificas', to='posts.postagem')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('postagem', 'nome')},
            },
        ),
    ]
