# Generated by Django 5.2 on 2025-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reacao_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=models.CharField(default='#888888', max_length=20),
        ),
    ]
