# Generated by Django 5.2 on 2025-05-23 15:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_tag_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
