# Generated by Django 5.2 on 2025-06-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_create_sample_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReacaoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reacao')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='posts.reply')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reação em Reply',
                'verbose_name_plural': 'Reações em Replies',
                'unique_together': {('reply', 'usuario')},
            },
        ),
    ]
