# Generated by Django 5.2 on 2025-05-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_reacao_alter_tag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200, verbose_name='Palavras-chave')),
                ('apenas_titulo', models.BooleanField(default=False, verbose_name='Pesquisar apenas por título')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('min_respostas', models.PositiveIntegerField(default=0, verbose_name='Número mínimo de respostas')),
                ('subforum', models.CharField(blank=True, max_length=100, verbose_name='Pesquisar no Fórum')),
                ('ordenacao', models.CharField(choices=[('relevance', 'Relevância'), ('date', 'Data'), ('replies', 'Mais Respondidos')], default='relevance', max_length=20, verbose_name='Ordenar por')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UltimaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVO_POST', 'Novo Post'), ('NOVA_REPLY', 'Nova Resposta'), ('NOVA_REACAO', 'Nova Reação')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='posts.postagem')),
                ('reacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='posts.reacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Última Atividade',
                'verbose_name_plural': 'Últimas Atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
