# Generated by Django 5.2 on 2025-07-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('posts', '0007_reacaoreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimaatividade',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='posts.reply'),
        ),
        migrations.AlterField(
            model_name='ultimaatividade',
            name='postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='posts.postagem'),
        ),
        migrations.AlterField(
            model_name='ultimaatividade',
            name='tipo',
            field=models.CharField(choices=[('NOVO_POST', 'Novo Post'), ('NOVA_REPLY', 'Nova Resposta'), ('NOVA_REACAO_POST', 'Nova Reação em Post'), ('NOVA_REACAO_REPLY', 'Nova Reação em Reply'), ('NOVO_THREAD', 'Novo Tópico')], max_length=25),
        ),
    ]
