# Generated by Django 5.2 on 2025-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ultimaatividade_reply_alter_ultimaatividade_postagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Record de Usuários Online',
            },
        ),
    ]
