# Generated by Django 5.2 on 2025-06-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dias_ganhos',
        ),
    ]
