# Generated by Django 5.2 on 2025-07-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_dias_ganhos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('pagina_atual', models.CharField(blank=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Online',
                'verbose_name_plural': 'Usuários Online',
                'ordering': ['-ultima_atividade'],
            },
        ),
    ]
