# Generated by Django 5.2 on 2025-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuarioonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_real',
            field=models.CharField(blank=True, help_text='Nome real (editável)', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posts_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de posts e threads'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='answers',
            field=models.PositiveIntegerField(default=0, help_text='Número de respostas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, verbose_name='Sobre mim'),
        ),
    ]
